version: "3.3"

services:
 nginx:
  image: nginx
  container_name: nginx
  restart: always
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./www:/var/www
   - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
  depends_on:
   - php
  networks:
   - app-network

 php:
  image: php:7-fpm
  container_name: phpfpm
  restart: always
  ports:
   - "9000:9000"
  volumes:
   - ./www:/var/www
  networks:
   - app-network

networks:
 app-network:
  driver: bridge
